name: Release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 21

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Zip build folder
        run: yarn build::zip

      - name: Publish build folder to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dream-canteen.zip
          prerelease: true
          asset_name: dream-canteen.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: true
          skip_build: true